# Generated by Django 4.1.4 on 2022-12-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('expenses', models.FloatField(default=0)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ename', models.CharField(max_length=100)),
                ('eamount', models.FloatField()),
                ('pay_mode', models.CharField(choices=[('CASH', 'CASH'), ('DEBIT-CARD', 'DEBIT-CARD'), ('CREDIT-CARD', 'CREDIT-CARD'), ('ONLINE-BANKING', 'ONLINE-BANKING'), ('UPI', 'UPI')], max_length=100)),
                ('expense_type', models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('RENT', 'RENT'), ('HOME', 'HOME'), ('EMI', 'EMI'), ('Other', 'Other')], max_length=100)),
                ('bill_receipt', models.FileField(blank=True, upload_to='documents/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
