# Generated by Django 4.1.4 on 2022-12-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bill_receipt',
        ),
    ]
